[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
APP_ENV = "production"
APP_DEBUG = "false"